/**
 * setup-config.js — Config Bridge
 * ================================
 * Reads secrets from .env and generates dashboard/config.js
 * so the vanilla JS frontend can access them without hardcoding.
 *
 * Usage:  node setup-config.js
 * Output: dashboard/config.js  (git-ignored)
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Parse .env manually (no dependencies needed)
const envPath = resolve(__dirname, '.env');
const envContent = readFileSync(envPath, 'utf-8');
const env = {};
for (const line of envContent.split('\n')) {
  const trimmed = line.trim();
  if (!trimmed || trimmed.startsWith('#')) continue;
  const eqIndex = trimmed.indexOf('=');
  if (eqIndex === -1) continue;
  const key = trimmed.slice(0, eqIndex).trim();
  const value = trimmed.slice(eqIndex + 1).trim();
  env[key] = value;
}

// Generate the frontend config file
const configContent = `/**
 * AUTO-GENERATED by setup-config.js — DO NOT EDIT MANUALLY
 * Re-generate: node setup-config.js
 * This file is git-ignored to protect secrets.
 */
window.NEXGATE_CONFIG = {
  GEMINI_API_KEY_CHATBOT: "${env.GEMINI_API_KEY_CHATBOT || ''}",
  FIREBASE: {
    apiKey: "${env.FIREBASE_API_KEY || ''}",
    authDomain: "${env.FIREBASE_AUTH_DOMAIN || ''}",
    databaseURL: "${env.FIREBASE_DATABASE_URL || ''}",
    projectId: "${env.FIREBASE_PROJECT_ID || ''}",
    storageBucket: "${env.FIREBASE_STORAGE_BUCKET || ''}",
    messagingSenderId: "${env.FIREBASE_MESSAGING_SENDER_ID || ''}",
    appId: "${env.FIREBASE_APP_ID || ''}",
    measurementId: "${env.FIREBASE_MEASUREMENT_ID || ''}"
  }
};
`;

const outPath = resolve(__dirname, 'dashboard', 'config.js');
writeFileSync(outPath, configContent, 'utf-8');
console.log(`[OK] Generated dashboard/config.js from .env`);
